'use strict';

angular.module('brainedIoApp')

.value('FunctionalAreas', {
  'Executive Function': [{
    regionName: 'brodmann9',
    opacity: '100',
    color: '#FA2B31'
  }, {
    regionName: 'brodmann10',
    opacity: '100',
    color: '#FA2B31'
  }, {
    regionName: 'brodmann11',
    opacity: '100',
    color: '#FA2B31'
  }, {
    regionName: 'brodmann24',
    opacity: '100',
    color: '#FA2B31'
  }, {
    regionName: 'brodmann25',
    opacity: '100',
    color: '#FA2B31'
  }, {
    regionName: 'brodmann32',
    opacity: '100',
    color: '#FA2B31'
  }, {
    regionName: 'brodmann33',
    opacity: '100',
    color: '#FA2B31'
  }, {
    regionName: 'brodmann45',
    opacity: '100',
    color: '#FA2B31'
  }, {
    regionName: 'brodmann46',
    opacity: '100',
    color: '#FA2B31'
  }, {
    regionName: 'brodmann47',
    opacity: '100',
    color: '#FA2B31'
  }],
  'Memory': [{
    regionName: 'brodmann20',
    opacity: '100',
    color: '#00DCE6'
  }, {
    regionName: 'brodmann23',
    opacity: '100',
    color: '#00DCE6'
  }, {
    regionName: 'brodmann26',
    opacity: '100',
    color: '#00DCE6'
  }, {
    regionName: 'brodmann28',
    opacity: '100',
    color: '#00DCE6'
  }, {
    regionName: 'brodmann29',
    opacity: '100',
    color: '#00DCE6'
  }, {
    regionName: 'brodmann30',
    opacity: '100',
    color: '#00DCE6'
  }, {
    regionName: 'brodmann31',
    opacity: '100',
    color: '#00DCE6'
  }, {
    regionName: 'brodmann34',
    opacity: '100',
    color: '#00DCE6'
  }, {
    regionName: 'brodmann35',
    opacity: '100',
    color: '#00DCE6'
  }, {
    regionName: 'brodmann36',
    opacity: '100',
    color: '#00DCE6'
  }],
  'Motor': [{
    regionName: 'brodmann4',
    opacity: '100',
    color: '#C3E91D'
  }, {
    regionName: 'brodmann6',
    opacity: '100',
    color: '#C3E91D'
  }, {
    regionName: 'brodmann8',
    opacity: '100',
    color: '#C3E91D'
  }],
  'Spatial Orientation': [{
    regionName: 'brodmann7',
    opacity: '100',
    color: '#008C78'
  }, {
    regionName: 'brodmann37',
    opacity: '100',
    color: '#008C78'
  }, {
    regionName: 'brodmann38',
    opacity: '100',
    color: '#008C78'
  }, {
    regionName: 'brodmann39',
    opacity: '100',
    color: '#008C78'
  }],
  'Language': [{
    regionName: 'brodmann20',
    opacity: '100',
    color: '#FF5E35'
  }, {
    regionName: 'brodmann21',
    opacity: '100',
    color: '#FF5E35'
  }, {
    regionName: 'brodmann22',
    opacity: '100',
    color: '#FF5E35'
  }, {
    regionName: 'brodmann39',
    opacity: '100',
    color: '#FF5E35'
  }, {
    regionName: 'brodmann40',
    opacity: '100',
    color: '#FF5E35'
  }, {
    regionName: 'brodmann41',
    opacity: '100',
    color: '#FF5E35'
  }, {
    regionName: 'brodmann42',
    opacity: '100',
    color: '#FF5E35'
  }, {
    regionName: 'brodmann44',
    opacity: '100',
    color: '#FF5E35'
  }, {
    regionName: 'brodmann45',
    opacity: '100',
    color: '#FF5E35'
  }, {
    regionName: 'brodmann47',
    opacity: '100',
    color: '#FF5E35'
  }],
  'Limbic': [{
    regionName: 'brodmann11',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann23',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann24',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann25',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann26',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann28',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann29',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann30',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann31',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann32',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann33',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann34',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann35',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann36',
    opacity: '100',
    color: '#BF1D4A'
  }, {
    regionName: 'brodmann52',
    opacity: '100',
    color: '#BF1D4A'
  }, ],
  'Somatosensory': [{
    regionName: 'brodmann1',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann2',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann3',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann5',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann17',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann18',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann19',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann21',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann22',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann27',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann37',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann38',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann40',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann41',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann42',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann43',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann44',
    opacity: '100',
    color: '#FDC312'
  }, {
    regionName: 'brodmann52',
    opacity: '100',
    color: '#FDC312'
  }]
});